# Read about `build.yaml` at https://pub.flutter-io.cn/packages/build_config
targets:
  $default:
    builders:
      bean_factory_generator|bean_factory_scan:
        enabled: true
        options:
          ignore_for_file: ['**.aymtools.dart','**.beanfactory.dart']
        generate_for:
          exclude: ['**.bf.aymtools.dart']
#      bean_factory_generator|bean_factory_export_lib:
#        enabled: false
#        options: { 'write': true }
#        generate_for:
#          exclude: ['**.bf.aymtools.dart']
      bean_factory_generator|bean_factory:
        enabled: true
        options: { 'write': true }
        generate_for:
          exclude: ['**.bf.aymtools.dart']
      bean_factory_generator|bean_factory_init:
        enabled: true
        generate_for:
          exclude: ['**.beanfactory.dart']
#    post_process_builders:
#      bean_factory_generator|bean_factory_init:
#        enabled: true
#        generate_for:
#          exclude: ['**..beanfactory.dart']

builders:

#  bean_factory_export_lib:
#    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
#    builder_factories: ['beanFactoryExport']
#    build_extensions: { '.aymtools.dart': ['.e.bf.aymtools.dart'] }
#    #    is_optional: true
#    #    runs_before: ['bean_factory_gen_sys_creator_builder']
#    #    applies_builders: ['bean_factory_scan_lib_creator_builder']
#    auto_apply: root_package
#    build_to: cache
  bean_factory:
    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
    builder_factories: ['beanFactory']
    build_extensions: { '.aymtools.dart': ['.bf.aymtools.dart'] }
    #    is_optional: true
    #    applies_builders: ['bean_factory_gen_sys_creator_builder']
    auto_apply: root_package
    build_to: source
  bean_factory_scan:
    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
    builder_factories: ['scanBean']
    build_extensions: { '.dart': ['.scan.bf.aymtools.dart'] }
    #    is_optional: true
    runs_before: ['bean_factory_generator|bean_factory']
#    applies_builders: ['bean_factory_generator|bean_factory_init']
#    auto_apply: all_packages
    auto_apply: root_package
    build_to: cache

  bean_factory_init:
    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
    builder_factories: ['init']
    build_extensions: { '.beanfactory.dart': ['.init.bf.aymtools.dart'] }
    runs_before: ['bean_factory_generator|bean_factory_scan']
    auto_apply: root_package
    build_to: cache

#post_process_builders:
#  bean_factory_init:
#    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
#    builder_factory: 'init'
#    input_extensions: [".beanfactory.dart"]
#    runs_before: ['bean_factory_generator|bean_factory_scan']
#    auto_apply: root_package
#    build_to: cache