# Read about `build.yaml` at https://pub.flutter-io.cn/packages/build_config
# import指定了builder的位置，
# builder_factories指定了builder的具体调用，
# build_extensions指定了输入输入文件的格式匹配，
builders:
  bean_factory_init_builder:
    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
    builder_factories: ['initBuilder']
    build_extensions: { '.dart': ['.init.bf.aymtools.dart'] }
    auto_apply: root_package
    build_to: cache
  #  class_template_builder:
  #    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
  #    builder_factories: ['classTemplateBuilder']
  #    build_extensions: { '.dart': ['.template.aymtools.dart'] }
  #    auto_apply: root_package
  #    build_to: source
  bean_factory_scan_bean_builder:
    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
    builder_factories: ['scanBeanBuilder']
    build_extensions: { '.dart': ['.scan.bf.aymtools.dart'] }
    auto_apply: root_package
    build_to: cache
  bean_factory_scan_lib_bean_builder:
    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
    builder_factories: ['scanLibBeanBuilder']
    build_extensions: { '.dart': ['.scan.lib.bf.aymtools.dart'] }
    auto_apply: root_package
    build_to: cache
  bean_factory_scan_creator_builder:
    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
    builder_factories: ['scanCreatorBuilder']
    build_extensions: { '.dart': ['.scan.creator.bf.aymtools.dart'] }
    auto_apply: root_package
    build_to: cache
  bean_factory_scan_lib_creator_builder:
    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
    builder_factories: ['scanLibCreatorBuilder']
    build_extensions: { '.dart': ['.scan.lib.creator.bf.aymtools.dart'] }
    auto_apply: root_package
    build_to: cache
  bean_factory_export_builder:
    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
    builder_factories: ['beanFactoryExportBuilder']
    build_extensions: { '.dart': ['.e.bf.aymtools.dart'] }
    auto_apply: root_package
    build_to: cache
  bean_factory_gen_sys_creator_builder:
    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
    builder_factories: ['genSysCreatorBuilder']
    build_extensions: { '.dart': ['.sys.bf.aymtools.dart'] }
    auto_apply: root_package
    build_to: source
  bean_factory_builder:
    import: 'package:bean_factory_generator/src/com/aymtools/beanfactory/builder.dart'
    builder_factories: ['beanFactoryBuilder']
    build_extensions: { '.dart': ['.bf.aymtools.dart'] }
    auto_apply: root_package
    build_to: source