name: bean_factory_generator
description: Bean factory generator Dart libraries.A pre-compiled class image containing the contents of the constructor, methods, and properties. Need to use with bean_factory.
version: 1.1.0
homepage: https://github.com/aymtools/flutter-bean-factory

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dependencies:
#  flutter:
#    sdk: flutter
  analyzer: ">=0.39.0 <0.40.0"
  build: ^1.0.0
  dart_style: ^1.0.0
  source_gen: ^0.9.4+4
  mustache4dart: ^3.0.0-dev.1.0
  bean_factory:
    path: ../bean-factory

dev_dependencies:
  build_runner: ^1.1.1

#flutter:
#  uses-material-design: true