name: bean_factory
description: Bean factory core Dart libraries.A pre-compiled class image containing the contents of the constructor, methods, and properties. Need to use with bean_factory_generator.
version: 1.0.1
homepage: https://github.com/aymtools/flutter-bean-factory

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dependencies:
#  flutter:
#    sdk: flutter

dev_dependencies:

#flutter:
#  uses-material-design: true